### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by hishamkaram** [kartoza/docker-postgis#55]
I have this configration in docker-compose.yml : 
```
version: '2'

services:
  postgis:
    image: kartoza/postgis
    restart: always
    env_file:
      - ./postgis.env
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
```
and in make file : 

```
up:
	# bring up the services
	docker-compose up -d

sync: up
	# set up the database tablea
	docker-compose exec cartoview python manage.py makemigrations app_manager
	docker-compose exec cartoview python manage.py migrate people
	docker-compose exec cartoview python manage.py migrate
```
when i run : 
`make sync `
this error appear : 
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "172.18.0.4", user "docker", database "cartoview", SSL on
FATAL:  no pg_hba.conf entry for host "172.18.0.4", user "docker", database "cartoview", SSL off

Makefile:6: recipe for target 'sync' failed

```

**Comment by timlinux** [comment]
Hi Sorry for the very slow reply. Did you resolve this issue? It looks like you need to add the 172.18.0 network in your pg_hba.conf file.  Are you running in boot to docker or what is your environment?

**Comment by hishamkaram** [comment]
I solved the problem by editing setup.sh 
I am running on ubuntu 16.04

**Comment by narnikgamarnikus** [comment]
@hishamkaram
I ran into the same problem.
In one of my projects everything worked as it should, in the other, on the same day, I got this error.
How did you manage to solve it?

**Comment by narnikgamarnikus** [comment]
If I add 
`echo "host    all             all             172.18.0.4/16               md5" >> /etc/postgresql/9.5/main/pg_hba.conf` to setup.sh , a get  `django_1    | Postgres is unavailable - sleeping`

**Comment by hishamkaram** [comment]
You can use this one https://hub.docker.com/r/cartoview/cartoview-postgis/
Forked from kartoza image and working fine

**Comment by hishamkaram** [comment]
But be careful this image listen to all requests so you can access db
remotly

**Comment by narnikgamarnikus** [comment]
@hishamkaram thanks you
